name: Quality (Node)

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: "20"
      runs-on:
        required: false
        type: string
        default: "ubuntu-latest"
      install-command:
        description: "Command used to install dependencies"
        required: false
        type: string
        default: "npm ci"
      lint-command:
        required: false
        type: string
        default: "npm run lint"
      test-command:
        required: false
        type: string
        default: ""
      working-directory:
        required: false
        type: string
        default: "."

jobs:
  lint:
    name: Lint
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"
          cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

      - name: Install dependencies
        env:
          INSTALL_CMD: ${{ inputs.install-command }}
        run: $INSTALL_CMD

      - name: Run linter
        env:
          LINT_CMD: ${{ inputs.lint-command }}
        run: $LINT_CMD

  test:
    name: Test
    if: ${{ inputs.test-command != '' }}
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"
          cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

      - name: Install dependencies
        env:
          INSTALL_CMD: ${{ inputs.install-command }}
        run: $INSTALL_CMD

      - name: Run tests
        env:
          TEST_CMD: ${{ inputs.test-command }}
        run: $TEST_CMD
